version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ncri
      POSTGRES_PASSWORD: ncri
      POSTGRES_DB: ncri
    ports:
      - "5432:5432"
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8000:8000"

volumes:
  postgres_data:
