services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ncri
      POSTGRES_PASSWORD: ncri
      POSTGRES_DB: ncri
    ports:
      - "5432:5432"
volumes:
  postgres_data:
