"""tweets

Revision ID: c3aa5e2ca853
Revises:
Create Date: 2024-05-06 11:13:09.935567

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c3aa5e2ca853"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tweets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author", sa.String(), nullable=True),
        sa.Column("author_created_utc", sa.DateTime(), nullable=True),
        sa.Column("clean_text", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("datetime", sa.DateTime(), nullable=True),
        sa.Column("day", sa.Integer(), nullable=True),
        sa.Column("follower_count", sa.Integer(), nullable=True),
        sa.Column("full_text", sa.String(), nullable=True),
        sa.Column("hateful", sa.Boolean(), nullable=True),
        sa.Column("lang", sa.String(), nullable=True),
        sa.Column("len_filter", sa.Boolean(), nullable=True),
        sa.Column("minute", sa.Integer(), nullable=True),
        sa.Column("month", sa.Integer(), nullable=True),
        sa.Column("reply_count", sa.Integer(), nullable=True),
        sa.Column("retweet_count", sa.Integer(), nullable=True),
        sa.Column("retweeted", sa.Boolean(), nullable=True),
        sa.Column("second", sa.Integer(), nullable=True),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("threat_level", sa.String(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("year_month", sa.String(), nullable=True),
        sa.Column("year_month_day", sa.String(), nullable=True),
        sa.Column("zip", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tweets_author"), "tweets", ["author"], unique=False)
    op.create_index(
        op.f("ix_tweets_created_at"), "tweets", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_tweets_datetime"), "tweets", ["datetime"], unique=False)
    op.create_index(op.f("ix_tweets_day"), "tweets", ["day"], unique=False)
    op.create_index(op.f("ix_tweets_hateful"), "tweets", ["hateful"], unique=False)
    op.create_index(op.f("ix_tweets_lang"), "tweets", ["lang"], unique=False)
    op.create_index(
        op.f("ix_tweets_len_filter"), "tweets", ["len_filter"], unique=False
    )
    op.create_index(op.f("ix_tweets_minute"), "tweets", ["minute"], unique=False)
    op.create_index(op.f("ix_tweets_month"), "tweets", ["month"], unique=False)
    op.create_index(
        op.f("ix_tweets_threat_level"), "tweets", ["threat_level"], unique=False
    )
    op.create_index(op.f("ix_tweets_year"), "tweets", ["year"], unique=False)
    op.create_index(
        op.f("ix_tweets_year_month"), "tweets", ["year_month"], unique=False
    )
    op.create_index(
        op.f("ix_tweets_year_month_day"), "tweets", ["year_month_day"], unique=False
    )
    op.create_index(op.f("ix_tweets_zip"), "tweets", ["zip"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tweets_zip"), table_name="tweets")
    op.drop_index(op.f("ix_tweets_year_month_day"), table_name="tweets")
    op.drop_index(op.f("ix_tweets_year_month"), table_name="tweets")
    op.drop_index(op.f("ix_tweets_year"), table_name="tweets")
    op.drop_index(op.f("ix_tweets_threat_level"), table_name="tweets")
    op.drop_index(op.f("ix_tweets_month"), table_name="tweets")
    op.drop_index(op.f("ix_tweets_minute"), table_name="tweets")
    op.drop_index(op.f("ix_tweets_len_filter"), table_name="tweets")
    op.drop_index(op.f("ix_tweets_lang"), table_name="tweets")
    op.drop_index(op.f("ix_tweets_hateful"), table_name="tweets")
    op.drop_index(op.f("ix_tweets_day"), table_name="tweets")
    op.drop_index(op.f("ix_tweets_datetime"), table_name="tweets")
    op.drop_index(op.f("ix_tweets_created_at"), table_name="tweets")
    op.drop_index(op.f("ix_tweets_author"), table_name="tweets")
    op.drop_table("tweets")
    # ### end Alembic commands ###
